"""Add gender_probability to profile

Revision ID: 0eb717350f90
Revises: a9f13d908b40
Create Date: 2026-04-17 15:14:18.054350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eb717350f90'
down_revision: Union[str, Sequence[str], None] = 'a9f13d908b40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('gender_probability', sa.Float(), nullable=True))
    op.drop_column('profile', 'gender_probabilities')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('gender_probabilities', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('profile', 'gender_probability')
    # ### end Alembic commands ###
