"""Change country_id from UUID to String

Revision ID: cab86370a969
Revises: e84a9c22a331
Create Date: 2026-04-17 15:22:42.225712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cab86370a969'
down_revision: Union[str, Sequence[str], None] = 'e84a9c22a331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile', 'country_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile', 'country_id',
               existing_type=sa.String(length=10),
               type_=sa.UUID(),
               existing_nullable=True)
    # ### end Alembic commands ###
