"""Add missing columns to profile

Revision ID: e84a9c22a331
Revises: 0eb717350f90
Create Date: 2026-04-17 15:17:04.818700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e84a9c22a331'
down_revision: Union[str, Sequence[str], None] = '0eb717350f90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'created_at')
    # ### end Alembic commands ###
